import type { NextConfig } from "next";

const nextConfig: NextConfig = {
    output: 'standalone',
    images: {
        remotePatterns: [
            { protocol: 'https', hostname: 'upload.wikimedia.org' },
            { protocol: 'https', hostname: 's7ap1.scene7.com' },
            { protocol: 'https', hostname: 'himachaltourstravel.com' },
            { protocol: 'https', hostname: 'i.ytimg.com' },
            { protocol: 'https', hostname: 'i0.wp.com' },
            { protocol: 'https', hostname: 'indiano.travel' },
            { protocol: 'https', hostname: 'weekendyaari.in' },
            { protocol: 'https', hostname: 'dynamic-media-cdn.tripadvisor.com' },
            { protocol: 'https', hostname: 'lp-cms-production.imgix.net' },
            { protocol: 'https', hostname: 'www.sacredyatra.com' },
            { protocol: 'https', hostname: 'uttarakhandtourism.gov.in' },
            { protocol: 'https', hostname: 'media.easemytrip.com' },
            { protocol: 'https', hostname: 'voyagersadventure.com' },
            { protocol: 'https', hostname: 'www.kurumatravels.com' },
            { protocol: 'https', hostname: 'himalayandaredevils.com' },
            { protocol: 'https', hostname: 'media.moxtain.com' },
            { protocol: 'https', hostname: 'trekthehimalayas.com' },
            { protocol: 'https', hostname: 'media-cdn.tripadvisor.com' },
            { protocol: 'https', hostname: 'www.karandesertsafarijaisalmer.com' },
            { protocol: 'https', hostname: 'www.tourmyindia.com' },
            { protocol: 'https', hostname: 'www.go2ladakh.in' },
            { protocol: 'https', hostname: 'discoverlehladakh.in' },
            { protocol: 'https', hostname: 'sceneloc8.com' },
            { protocol: 'https', hostname: 'mytriphack.com' },
            { protocol: 'https', hostname: 'discovery.sndimg.com' },
            { protocol: 'https', hostname: 'darjeelingyatra.com' },
            { protocol: 'https', hostname: 'www.darjeeling-tourism.com' },
            { protocol: 'https', hostname: 'samaaratea.com' },
            { protocol: 'https', hostname: 'images.unsplash.com' },
            { protocol: 'https', hostname: 'img.avianexperiences.com' },
            { protocol: 'https', hostname: 'captureatrip-cms-storage.s3.ap-south-1.amazonaws.com' },
            { protocol: 'https', hostname: 's3.amazonaws.com' },
            { protocol: 'https', hostname: 'businessfirst.travel' },
            { protocol: 'https', hostname: 'cdn.motor1.com' },
            { protocol: 'https', hostname: 'media.flytographer.com' },
            { protocol: 'https', hostname: 'etimg.etb2bimg.com' },
            { protocol: 'https', hostname: 'indiannewsandtimes.com' },
            { protocol: 'https', hostname: 'i.pinimg.com' },
            { protocol: 'https', hostname: 'www.gorspa.org' },
            { protocol: 'https', hostname: 'images.squarespace-cdn.com' },
            { protocol: 'https', hostname: 'media.tacdn.com' },
            { protocol: 'https', hostname: 'img1.wsimg.com' },
            { protocol: 'https', hostname: 'cms-artifacts.motionarray.com' },
            { protocol: 'https', hostname: 'peopleoftheplanet.com' },
            { protocol: 'https', hostname: 'static.toiimg.com' },
            { protocol: 'https', hostname: 'tinypic.com' },
            { protocol: 'https', hostname: 'www.madornomad.com' },
            { protocol: 'https', hostname: 'www.elegantjourneys.com' },
            { protocol: 'https', hostname: 'stampedmoments.com' },
            { protocol: 'https', hostname: 'randomuser.me' },
        ],
    },
};

export default nextConfig;
